name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Install dependencies
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      # Run tests
      - name: Run tests
        working-directory: ./frontend
        run: npm test --if-present

      # Build project
      - name: Build project
        working-directory: ./frontend
        run: npm run build

      # Upload artifact for CodePipeline
      - name: Zip frontend build
        run: |
          cd frontend/dist
          zip -r ../../frontend-build.zip .

      - name: Upload artifact to S3 for CodePipeline
        run: aws s3 cp frontend-build.zip s3://$S3_BUCKET/frontend-build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          S3_BUCKET: ${{ secrets.AWS_CODEPIPELINE_ARTIFACT_BUCKET }}

      # Trigger CodePipeline
      - name: Trigger AWS CodePipeline
        run: aws codepipeline start-pipeline-execution --name ${{ secrets.AWS_CODEPIPELINE_FRONTEND }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
